server:
  port: 17102

spring:
  application:
    name: boot2-test
  datasource:
    url: jdbc:mysql://localhost:3306/simple_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
      test-while-idle: true
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
