server:
  port: 17100

spring:
  application:
    name: boot2-redis
#  redis 的配置
  redis:
    # 连接超时时间（毫秒）
    timeout: 1000
    #哨兵 没环境，待验证
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 8
#        min-idle: 0
#    sentinel:
#      master: mymaster
#      nodes: 192.168.10.114:6379
    #单节点
    database: 0
    host: 192.168.10.114
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

